[package]
name = "server"
version = "0.1.0"
authors = ["shockham <samuel.hockham@gmail.com>"]
edition = "2018"

[dependencies]
warp = "0.3"
futures = "0.3"
tokio = { version = "1.0", features = ["full"] }
